name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        
        - name: Install dependencies
          run: npm install
        - name: Check style
          run: npm run eslint
        - name: Check build
          run: npm run build
        - name: Check tests
          run: npm test
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests
          run: npm run test:e2e
        - name: Trigger deployment
          env:
           COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
           CONDITION: ${{ contains(github.env.COMMIT_MESSAGES, '#skip')}}
          if: ${{github.event_name == 'push' && env.CONDITION == 'false'}}
          run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
          
        - name: Deployment succes
          env:
             COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
             CONDITION: ${{ contains(github.env.COMMIT_MESSAGES, '#skip')}}
          
          if: ${{github.event_name == 'push' && env.CONDITION == 'false' && success()}}
          uses: rjstone/discord-webhook-notify@v1
          with:
      
            severity: info
            text: A new version of Pokedex deployed!
            details: Deployment Succeeded!
            description: by ${{ github.actor }}
            username: Pokedex Notify
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Deployment failure
          env:
             COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
             CONDITION: ${{ contains(github.env.COMMIT_MESSAGES, '#skip')}}
         
          if: ${{github.event_name == 'push' && env.CONDITION == 'false' && failure()}}
          uses: rjstone/discord-webhook-notify@v1
          with:
      
            severity: info
            text: Pokedex deployment failed!
            details: Deployment Failed!
            description: by ${{ github.actor }}
            
            username: Pokedex Notify
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
            node-version: '20'
       - name: Bump version and push tag
         env:
           COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
           CONDITION: ${{ contains(github.env.COMMIT_MESSAGES, '#skip')}}
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           DEFAULT_BUMP: patch
         if: ${{github.event_name == 'push' && env.CONDITION == 'false'}}
         uses: anothrNick/github-tag-action@1.71.0
         
    
       
        
